# Generated by Django 3.2.8 on 2021-11-08 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pretalx.common.mixins.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0033_auto_20211018_0052'),
        ('person', '0025_drop_unused_speakerinformation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='event.event')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(pretalx.common.mixins.models.LogMixin, models.Model),
        ),
    ]
