# Generated by Django 3.2.8 on 2021-11-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0027_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
