# Generated by Django 3.2.8 on 2021-11-16 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0063_remove_track_color'),
        ('person', '0028_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='submission.track'),
        ),
    ]
