# Generated by Django 3.2.8 on 2021-10-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0059_remove_question_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cfp',
            name='default_type',
        ),
        migrations.AddField(
            model_name='cfp',
            name='is_start',
            field=models.BooleanField(default=False),
        ),
    ]
