# Generated by Django 3.2.8 on 2021-10-20 12:32

from django.db import migrations, models
import django.db.models.deletion
import i18nfield.fields
import pretalx.common.mixins.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0033_auto_20211018_0052'),
        ('submission', '0060_auto_20211019_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='CfT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('is_start', models.BooleanField(default=False)),
                ('headline', i18nfield.fields.I18nCharField(max_length=300, null=True)),
                ('text', i18nfield.fields.I18nTextField(null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='event.event')),
            ],
            bases=(pretalx.common.mixins.models.LogMixin, models.Model),
        ),
    ]
