# Generated by Django 3.2.8 on 2021-10-24 12:51

from django.db import migrations, models
import django.db.models.deletion
import i18nfield.fields
import pretalx.submission.models.track


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_auto_20211024_1251'),
        ('submission', '0061_cft'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='community_description',
            field=i18nfield.fields.I18nTextField(default=''),
        ),
        migrations.AddField(
            model_name='track',
            name='community_logo',
            field=models.ImageField(null=True, upload_to=pretalx.submission.models.track.logo_path),
        ),
        migrations.AddField(
            model_name='track',
            name='community_name',
            field=i18nfield.fields.I18nCharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='track',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.room'),
        ),
        migrations.AddField(
            model_name='track',
            name='state',
            field=models.CharField(default='submitted', max_length=9),
        ),
    ]
