# Generated by Django 3.2.8 on 2021-11-27 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0030_auto_20211127_0152'),
        ('submission', '0063_remove_track_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='submission_types',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='submission_type',
        ),
        migrations.RemoveField(
            model_name='submitteraccesscode',
            name='submission_type',
        ),
        migrations.DeleteModel(
            name='SubmissionType',
        ),
    ]
