# Generated by Django 3.2.8 on 2021-10-17 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0028_organiser_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organiser',
        ),
        migrations.AlterField(
            model_name='organiser',
            name='event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organiser', to='event.event'),
        ),
    ]
