# Generated by Django 3.2.8 on 2021-10-18 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0032_alter_event_organiser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='all_events',
        ),
        migrations.RemoveField(
            model_name='team',
            name='can_create_events',
        ),
        migrations.RemoveField(
            model_name='team',
            name='limit_events',
        ),
    ]
