# Generated by Django 3.2.8 on 2021-11-20 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0009_queuedmail_locale'),
        ('event', '0033_auto_20211018_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ack_track_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mail.mailtemplate'),
        ),
    ]
