# Generated by Django 3.2.8 on 2021-10-24 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0061_cft'),
        ('schedule', '0014_schedule_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='submission.track'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
